[package]
name = "amm_q3"
version = "0.1.0"
description = "Created with Anchor"
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "amm_q3"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
anchor-debug = []
custom-heap = []
custom-panic = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "1.0.2", features = ["init-if-needed"] }
anchor-spl = "1.0.2"
config = "0.15.23"
cp-curve="0.1.0"
constant-product-curve = { git = "https://github.com/deanmlittle/constant-product-curve", package = "constant-product-curve" }


[dev-dependencies]
litesvm = "0.12.0"
solana-message = "4.1.1"
solana-transaction = "3.1.0"
solana-signer = "3.0.0"
solana-keypair = "3.0.1"
solana-pubkey = "4.0.0"
litesvm-token = "0.12.0"
solana-sdk= "4.0.1" 



[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }